-- TABELA DE TENANT PARA TESTES
CREATE TABLE PUBLIC.TENANT (
    TENANT_ID           VARCHAR(30) NOT NULL,
    SCHEMA              VARCHAR(30) NOT NULL,

    CONSTRAINT TENANT_PKEY PRIMARY KEY (TENANT_ID)
);
